services:
  magento-currencyapi-tests:
    build: .
    volumes:
      - .:/app
      - /app/vendor  # Exclude vendor from volume mount for better performance
    environment:
      - PHPUNIT_ENV=testing
